// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/flashcard/FlashCard.snapshot.tsx": () => import("../components/mockups/flashcard/FlashCard.snapshot.tsx"),
  "./components/mockups/flashcard/FlashCard.tsx": () => import("../components/mockups/flashcard/FlashCard.tsx")
};
